version: "3.7"

services:
  node1:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    volumes:
      - ./app:/app
    working_dir: /app
    ports: 
      - 3000:3000
    expose:
      - 3000
    # stdin_open: true
    # tty: true
    networks:
      - fastapi-network
    environment:
      - NODE_NAME=node1

  node2:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 3001 --reload
    volumes:
      - ./app:/app
    working_dir: /app
    ports: 
      - 3001:3001
    expose:
      - 3001
    networks:
      - fastapi-network
    environment:
      - NODE_NAME=node2
  
  node3:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 3002 --reload
    volumes:
      - ./app:/app
    working_dir: /app
    ports: 
      - 3002:3002
    expose:
      - 3002
    networks:
      - fastapi-network
    environment:
      - NODE_NAME=node3

volumes:
  app:
    
networks:
  fastapi-network:
