version: "3.7"

services:
  node1:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    volumes:
      - ./app:/app
    working_dir: /app
    ports: 
      - 3000:3000
    networks:
      app-network:

  node2:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 3001 --reload
    volumes:
      - ./app:/app
    working_dir: /app
    ports: 
      - 3001:3001
    networks:
      app-network:
  
  node3:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 3002 --reload
    volumes:
      - ./app:/app
    working_dir: /app
    ports: 
      - 3002:3002
    networks:
      app-network:

volumes:
  app:
    
networks:
  app-network:
